### ISSUE TITLE
Consider mentioning HN discussion in 1st blog post

### ISSUE THREAD

**Issue by aschrijver** [benbjohnson/litestream.io#3]
I found Litestream via Hacker News, and in that thread a lot of additional background is discussed on running SQLite in production. It was really enlightening. Think it might be an idea to refer to the discussion thread from the blog post (and maybe even in project README).

https://news.ycombinator.com/item?id=26103776

**Comment by benbjohnson** [comment]
Thanks, @aschrijver. That's a good idea. I updated the post with a link at the bottom: https://github.com/benbjohnson/litestream.io/commit/1519cbb93d7afea8ac8f6d0d274d66c123c99507
