### ISSUE TITLE
`-if-db-not-exists` missing from the `restore` command documentation

### ISSUE THREAD

**Issue by heikkilamarko** [benbjohnson/litestream.io#41]
`-if-db-not-exists` is missing from the `restore` command documentation.

The `Arguments` section here: https://litestream.io/reference/restore/#arguments

**Comment by benbjohnson** [comment]
Thanks! Fixed via https://github.com/benbjohnson/litestream.io/commit/edde9a320fc629f143d7b5c3b6d43bdabd0c2c15
