### ISSUE TITLE
Unable to follow the Getting Started guide

### ISSUE THREAD

**Issue by randomor** [benbjohnson/litestream.io#45]
Was trying to follow this guide: https://litestream.io/getting-started/

Stuck at the replication step:

```
monitor error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
Do I have to config anything with MinIO or AWS CLI? Thanks!

**Comment by benbjohnson** [comment]
@randomor It sounds like you don't have the environment variables set in the terminal window you're running that command in:

```
export LITESTREAM_ACCESS_KEY_ID=minioadmin
export LITESTREAM_SECRET_ACCESS_KEY=minioadmin
```

**Comment by randomor** [comment]
I have those, but figured out finally that what I really need is:
```
export AWS_ACCESS_KEY_ID=minioadmin
export AWS_SECRET_ACCESS_KEY=minioadmin
```

Maybe the AWS go package will be looking for these?

**Comment by benbjohnson** [comment]
Ah, sorry, I misread your comment above that you were using the MinIO/AWS CLIs. Yes, that's the correct environment variables for those tools. 👍
