### ISSUE TITLE
Update cron docs to use VACUUM instead

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream.io#56]
Apparently the backup command is not transactional but VACUUM is.

**Comment by ignoramous** [comment]
> `VACUUM INTO` backups are transactional, but the `.backup` mechanism is not: https://news.ycombinator.com/item?id=31387556
>
> Ben I suggest updating that cron backups documentation page to recommend `VACUUM INTO` instead! 

[ref](https://news.ycombinator.com/item?id=31387557).

**Comment by simonw** [comment]
https://til.simonwillison.net/sqlite/compile-sqlite3-ubuntu is when I first figured this out:

    /home/simon/bin/sqlite3 data.db "vacuum into '/tmp/backup.db'"

**Comment by simonw** [comment]
I had a go at this in https://github.com/benbjohnson/litestream.io/pull/57

It looks like it's not quite as simple as "VACUUM INTO is always better than .backup" - there are some subtleties. https://www.sqlite.org/lang_vacuum.html#vacuuminto says

> The VACUUM command with an INTO clause is an alternative to the [backup API](https://www.sqlite.org/backup.html) for generating backup copies of a live database. The advantage of using VACUUM INTO is that the resulting backup database is minimal in size and hence the amount of filesystem I/O may be reduced. Also, all deleted content is purged from the backup, leaving behind no forensic traces. On the other hand, the [backup API](https://www.sqlite.org/backup.html) uses fewer CPU cycles and can be executed incrementally.

**Comment by simonw** [comment]
Something I don't understand is what "can be executed incrementally" refers to with regards to the backup API - maybe that's something you can do with the C interface that isn't relevant to running `.backup` using the SQLite CLI tool.

**Comment by simonw** [comment]
I found the implementation of the `.backup` command here: https://github.com/sqlite/sqlite/blob/96d5549778c369e723157498e26496144a1caeae/src/shell.c.in#L8132-L8199

**Comment by benbjohnson** [comment]
Merged. Thanks everybody!
