### ISSUE TITLE
guides/gcs: service account permissions

### ISSUE THREAD

**Issue by j0hnsmith** [benbjohnson/litestream.io#61]
Under the service account section it says

> Next, you'll need to grant the Storage Object Creator and Storage Object Viewer roles to your service accounts so they can read & write data. Then click the "Done" button.

I'm running continuous replication and I see a lot of messages like this in my logs

```
 /somepath.db(gcs): retainer error: snapshot: googleapi: Error 403: xxxxxxx@xxxxxxxxxxx.iam.gserviceaccount.com does not have storage.objects.delete access to the Google Cloud Storage object., forbidden
```

Removing the roles named above and adding the role `roles/storage.objectAdmin` has fixed the problem.

**Comment by benbjohnson** [comment]
Thanks! Fixed up.
